### ISSUE TITLE
required_conversation_resolution is ignored

### ISSUE THREAD

**Issue by toby-whitebox** [Hatzelencio/branch-protection#2]
If I set `required_conversation_resolution: true` the setting does not change. Possibly fixed in a newer version of go-github, but I'm not super familiar with go. https://github.com/google/go-github/releases/tag/v38.0.0

**Comment by Hatzelencio** [comment]
Hi @toby-whitebox, it's right, They added the flag `required_conversation_resolution` at `v37.0.0`. Unfortunately, I don't have enough time to upgrade the code base, but if you want to upgrade it (or someone), feel free to send a new PR. I assume what upgrades the `go-github` version will be straightforward.

**Comment by toby-whitebox** [comment]
@Hatzelencio I submitted a PR from my personal account. Let me know if any changes are needed.
